[package]
name = "sp-bls12-377"
version = "0.4.0-alpha"
authors = ["Parity Technologies <admin@parity.io>", "Achim Schneider <achim@parity.io>", "arkworks contributors" ]
repository = "https://github.com/paritytech/substrate-curves"
description = "The BLS12-377 pairing-friendly elliptic curve, optimized for Substrate"
keywords = ["cryptography", "finite-fields", "elliptic-curves", "substrate" ]
categories = ["cryptography"]
include = ["Cargo.toml", "src", "README.md", "LICENSE-APACHE", "LICENSE-MIT"]
license = "MIT/Apache-2.0"
edition = "2021"
publish = true

[dependencies]
sp-ark-bls12-377 = { git = "https://github.com/paritytech/ark-substrate",  features = ["curve"], default-features = false }
sp-crypto-ec-utils =  { git = "https://github.com/paritytech/polkadot-sdk", default-features = false }
ark-std = { version = "0.4.0", default-features = false }

[dev-dependencies]
ark-ff = { version = "0.4.2", default-features = false }
ark-relations = { version = "0.4.0", default-features = false }
ark-ec = { version = "0.4.2", default-features = false }
ark-algebra-test-templates = { version = "0.4.2", default-features = false }
ark-serialize = { version = "0.4.2", default-features = false }
codec = { package = "parity-scale-codec", version = "3.2.2", default-features = false }
ark-scale = { version = "0.0.11", features = ["hazmat"], default-features = false }
sp-ark-models = { git = "https://github.com/paritytech/ark-substrate",  default-features = false }

[features]
default = [ "std" ]
std = [ 
    "ark-ff/std", 
    "ark-std/std", 
    "sp-ark-bls12-377/std",
    "sp-ark-models/std",
    "codec/std",
    "ark-scale/std",
    "sp-crypto-ec-utils/std",
]

curve = [ "scalar_field", "base_field" ]
scalar_field = []
base_field = []
